name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version bump type (patch, minor, major)"
        required: true
        default: "patch"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Bump version
        run: pnpm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Get version
        id: pkg
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Get previous version
        id: prev
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --max-count=1) || echo "v0.0.0")
          echo "previous_version=${PREV_TAG}" >> $GITHUB_OUTPUT

      - name: Commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore(release): v${{ steps.pkg.outputs.version }}"

      - name: Create and push tag
        run: |
          git tag v${{ steps.pkg.outputs.version }}
          git push origin HEAD:main --tags

      - name: Create GitHub release (auto notes)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ steps.pkg.outputs.version }} \
            --generate-notes \
            --title "v${{ steps.pkg.outputs.version }}" \
            --target main
