name: Publish VS Code Theme

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install @vscode/vsce
        run: pnpm add -g @vscode/vsce

      - name: Show package version
        run: echo "Publishing version $(jq -r .version package.json)"

      - name: Publish to VS Code Marketplace
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: pnpm exec vsce publish -p "$VSCE_TOKEN"
