name: Publish VS Code Theme
on:
  push:
    tags: ["v*.*.*"] # triggers only on tags like v1.0.0, v2.1.3, etc.

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Show package version
        run: echo "Publishing version $(jq -r .version package.json)"

      - name: Publish to VS Code Marketplace
        run: pnpm exec vsce publish -p ${{ secrets.VSCE_TOKEN }}
